syntax = "proto3";

package tvShow;

message TVShow {
  string id = 1;
  string title = 2;
  string description = 3;
}

message GetTVShowRequest {
  string tv_show_id = 1;
}
message GetTVShowResponse {
  TVShow tv_show = 1;
}

message SearchTVShowsRequest {
  string query = 1;
}
message SearchTVShowsResponse {
  repeated TVShow tv_shows = 1;
}

message CreateTVShowRequest {
  string title = 1;
  string description = 2;
}
message CreateTVShowResponse {
  TVShow tv_show = 1;
}

message UpdateTVShowRequest {
  string tv_show_id = 1;
  string title = 2;
  string description = 3;
}
message UpdateTVShowResponse {
  TVShow tv_show = 1;
}

message DeleteTVShowRequest {
  string tv_show_id = 1;
}
message DeleteTVShowResponse {
  string message = 1;
}

service TVShowService {
  rpc GetTvshow(GetTVShowRequest) returns (GetTVShowResponse);
  rpc SearchTvshows(SearchTVShowsRequest) returns (SearchTVShowsResponse);
  rpc CreateTvshow(CreateTVShowRequest) returns (CreateTVShowResponse);
  rpc UpdateTvshow(UpdateTVShowRequest) returns (UpdateTVShowResponse);
  rpc DeleteTvshow(DeleteTVShowRequest) returns (DeleteTVShowResponse);
}